### ISSUE TITLE
Name Theft

### ISSUE THREAD

**Issue by darkfrog26** [Auginte/scarango#5]
I apologize, I only just realized that there was another project with the same name, but since it looks like you abandoned this I hope you can forgive the theft of your project's name: https://github.com/outr/scarango

If you take issue with the name collision please let me know and I'll come up with a new name. On the other hand, if you'd like to contribute to my new project I'd welcome the assistance.

**Comment by aurelijusb** [comment]
You are right about the `looks like you abandoned` part. So you are *free to use the `scarango` name* and make a more actively maintainable Scala driver for `ArangoDB` :smile: 

Just for documentation. Currently I do not have a real business use case, where my implementation of ArangoDB client fits the best. Therefore there were no improvements of the driver itself.

**Comment by darkfrog26** [comment]
Wonderful. If you should come up with a use-case or just feel like joining in I'd be happy to welcome you to my project.  Thanks.
